spring:
  application:
    name: easy-login
  freemarker:
    # req访问request
    request-context-attribute: request
    # 后缀名
    suffix: .ftl
    content-type: text/html
    enabled: true
    # 缓存配置
    cache: false
    # 模板加载路径 按需配置（这里就是我们上面的忽略配置）
    template-loader-path: classpath:/templates/
    # 编码格式
    charset: UTF-8
    settings:
      # 数字格式化，无小数点
      number_format: '0.##'
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

  redis:
    cluster:
      nodes: 10.150.30.214:6386,10.150.30.215:6386,10.150.30.216:6386,10.150.30.217:6386,10.150.30.218:6386,10.150.30.219:6386
      max-redirects: 6
    database: 15
    password: hengchang20200518
    jedis:
      pool:
        max-active: 300
        max-wait: 3000
        max-idle: 100

server:
  port: 8080
  servlet:
    context-path: /sso
    encoding:
      force: true

login:
  userInfoMap:
    chatgpt: credithc@admin
    gptadmin: idg@admin
    lvjietao: 1qazxsw2@admin
  token: 7cp4VkZ3Nju1AOjy

thymeleaf:
  prefix: classpath:/templates/
  suffix: .ftl
  cache: false


idg:
  rabbitmq:
    enabled: true
    nodes:
      - name: primary
        host: 10.100.13.142
        username: cuishou1
        password: cuishou999
        virtualHost: /credithc

      - name: secondary
        host: 10.100.13.142
        username: dddai
        password: dddai
        virtualHost: /dddai

    consumers:
      - connectionFactoryName: primary
        exchangeType: direct
        exchangeName: CREDITHC_INFRA
        routingKey: fdfk_order_request_test123
        queueName: fdfk_order_request_test123
        concurrency: 5
        prefetch: 2
        messageProcess: testConsumer

    producers:
      send2business:
        connectionFactoryName: primary
        exchangeType: direct
        exchangeName: CREDITHC_INFRA
        routingKey: fdfk_send_message_business_test123
        queueName: fdfk_send_message_business_test123

platform-security:
  appName: platform-security
  appPath: api/V1
  appUrl: http://infra-security-api.test.hcinner
  ps:
    enabled: true
    appkey: b1aa3358b1ba4c6388107b4430efcb8b
    appSecret: bf7bd9fca1f443aa87c6934151d61d8a